from .create_role import *
from .create_account import *
from .create_course_category import *
from .create_teacher_academic import *
from .create_teacher_degree import *
from .create_student import *
from .create_teacher import *
from .create_course import *
from .create_course_student import *
from .create_student_rating import *